work_dir: ./work_dir/recognition/kinetics_skeleton/ST_GCN

# ranknet feeder
ranknet_feeder: feeder.feeder.Feeder
ranknet_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150 
  data_path: ./data/Kinetics/kinetics-skeleton/train_data.npy
  label_path: ./data/Kinetics/kinetics-skeleton/train_label.pkl


# ranknet model
ranknet_model: net.st_gcn.Model
ranknet_args:
  in_channels: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# ranknet train
ranknet_train_arg:
  batch_size: 4
  base_lr: 0.01
  num_epoch: 100


process:
  exp_name: 'first_exp'
  round: 50
  person: 10
  pair_batch_size: 10
  
device: [0,1,2,3]
num_worker: 4
