work_dir: ./work_dir/recognition/kinetics_skeleton/ST_GCN

# feeder
ranknet_feeder: feeder.feeder.Feeder
ranknet_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150 
  data_path: ./data/Kinetics/kinetics-skeleton/train_data.npy


# model
ranknet_model: net.st_gcn.Model
ranknet_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0,1,2,3]
ranknet_batch_size: 4

#optim
base_lr: 0.01
step: [20, 30, 40, 50]
num_epoch: 50


process:
  exp_name: 'first_exp'
  round: 50
  person: 10
  pair_batch_size: 10
  
