work_dir: ./work_dir/recognition/kinetics_skeleton/ST_GCN

# ranknet feeder
ranknet_feeder: feeder.feeder.Feeder
ranknet_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150 
  data_path: ./data/Kinetics/train_data.npy
  label_path: ./data/Kinetics/train_label.pkl


# ranknet model
ranknet_model: net.st_gcn.Model
ranknet_args:
  in_channels: 3
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# ranknet train
ranknet_train_arg:
  batch_size: 32
  base_lr: 0.001
  num_epoch: 500

# stgec embed
embed_model: net.stgcn_embed.Model
embed_args:
  in_channels: 3
  out_channels: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'
  embed_path: ./data/embed/embedded.npy

# qnet
dqn_model: net.qnet.QNet
dqn_args:
  memory_size: 500
  batch_size: 50
  double_q: True
  gamma: 0.7
  tau: 0.01
  learning_rate: 0.001
  l2_norm: 0.001


process:
  exp_name: 'first_exp'
  round: 50
  person_per_batch: 1
  pair_batch_size: 100
  candi_num: 20
  update_times: 500

# data:
#   data_path: ./data/Kinetics/train_data.npy
#   label_path: ./data/Kinetics/train_label.pkl

pretrained:
  ranknet: './pretrain/ranknet/ranknet.pt'
  embed: './pretrain/dqn/embed.pt'

device: [0,1,2,3]
num_worker: 4
